/*
 * This file is generated by jOOQ.
 */
package meta.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import meta.tables.MailingList;
import meta.tables.interfaces.IMailingList;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MailingListRecord extends UpdatableRecordImpl<MailingListRecord> implements Record7<Long, String, String, String, String, Timestamp, Boolean>, IMailingList {

    private static final long serialVersionUID = -1368500466;

    /**
     * Setter for <code>public.mailing_list.id</code>.
     */
    @Override
    public MailingListRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.mailing_list.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mailing_list.affiliation</code>.
     */
    @Override
    public MailingListRecord setAffiliation(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.mailing_list.affiliation</code>.
     */
    @Override
    public String getAffiliation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.mailing_list.email</code>.
     */
    @Override
    public MailingListRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.mailing_list.email</code>.
     */
    @Override
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mailing_list.first_name</code>.
     */
    @Override
    public MailingListRecord setFirstName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.mailing_list.first_name</code>.
     */
    @Override
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mailing_list.last_name</code>.
     */
    @Override
    public MailingListRecord setLastName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.mailing_list.last_name</code>.
     */
    @Override
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mailing_list.created</code>.
     */
    @Override
    public MailingListRecord setCreated(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.mailing_list.created</code>.
     */
    @Override
    public Timestamp getCreated() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.mailing_list.receives_mail</code>.
     */
    @Override
    public MailingListRecord setReceivesMail(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.mailing_list.receives_mail</code>.
     */
    @Override
    public Boolean getReceivesMail() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, String, Timestamp, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, String, Timestamp, Boolean> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MailingList.MAILING_LIST.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MailingList.MAILING_LIST.AFFILIATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MailingList.MAILING_LIST.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MailingList.MAILING_LIST.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MailingList.MAILING_LIST.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return MailingList.MAILING_LIST.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return MailingList.MAILING_LIST.RECEIVES_MAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAffiliation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getReceivesMail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAffiliation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getReceivesMail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingListRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingListRecord value2(String value) {
        setAffiliation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingListRecord value3(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingListRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingListRecord value5(String value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingListRecord value6(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingListRecord value7(Boolean value) {
        setReceivesMail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MailingListRecord values(Long value1, String value2, String value3, String value4, String value5, Timestamp value6, Boolean value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IMailingList from) {
        setId(from.getId());
        setAffiliation(from.getAffiliation());
        setEmail(from.getEmail());
        setFirstName(from.getFirstName());
        setLastName(from.getLastName());
        setCreated(from.getCreated());
        setReceivesMail(from.getReceivesMail());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IMailingList> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MailingListRecord
     */
    public MailingListRecord() {
        super(MailingList.MAILING_LIST);
    }

    /**
     * Create a detached, initialised MailingListRecord
     */
    public MailingListRecord(Long id, String affiliation, String email, String firstName, String lastName, Timestamp created, Boolean receivesMail) {
        super(MailingList.MAILING_LIST);

        set(0, id);
        set(1, affiliation);
        set(2, email);
        set(3, firstName);
        set(4, lastName);
        set(5, created);
        set(6, receivesMail);
    }
}
