/*
 * This file is generated by jOOQ.
 */
package meta.tables.records;


import javax.annotation.Generated;

import meta.tables.Participant;
import meta.tables.interfaces.IParticipant;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParticipantRecord extends UpdatableRecordImpl<ParticipantRecord> implements Record5<Long, String, String, String, Long>, IParticipant {

    private static final long serialVersionUID = -1014909350;

    /**
     * Setter for <code>public.participant.id</code>.
     */
    @Override
    public ParticipantRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.participant.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.participant.name</code>.
     */
    @Override
    public ParticipantRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.participant.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.participant.email</code>.
     */
    @Override
    public ParticipantRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.participant.email</code>.
     */
    @Override
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.participant.verification_token</code>.
     */
    @Override
    public ParticipantRecord setVerificationToken(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.participant.verification_token</code>.
     */
    @Override
    public String getVerificationToken() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.participant.event_id</code>.
     */
    @Override
    public ParticipantRecord setEventId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.participant.event_id</code>.
     */
    @Override
    public Long getEventId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Participant.PARTICIPANT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Participant.PARTICIPANT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Participant.PARTICIPANT.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Participant.PARTICIPANT.VERIFICATION_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Participant.PARTICIPANT.EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getVerificationToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getVerificationToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value3(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value4(String value) {
        setVerificationToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value5(Long value) {
        setEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord values(Long value1, String value2, String value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IParticipant from) {
        setId(from.getId());
        setName(from.getName());
        setEmail(from.getEmail());
        setVerificationToken(from.getVerificationToken());
        setEventId(from.getEventId());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IParticipant> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParticipantRecord
     */
    public ParticipantRecord() {
        super(Participant.PARTICIPANT);
    }

    /**
     * Create a detached, initialised ParticipantRecord
     */
    public ParticipantRecord(Long id, String name, String email, String verificationToken, Long eventId) {
        super(Participant.PARTICIPANT);

        set(0, id);
        set(1, name);
        set(2, email);
        set(3, verificationToken);
        set(4, eventId);
    }
}
