/*
 * This file is generated by jOOQ.
 */
package meta.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IEvent extends Serializable {

    /**
     * Setter for <code>public.event.id</code>.
     */
    public IEvent setId(Long value);

    /**
     * Getter for <code>public.event.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.event.name</code>.
     */
    public IEvent setName(String value);

    /**
     * Getter for <code>public.event.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.event.contact</code>.
     */
    public IEvent setContact(String value);

    /**
     * Getter for <code>public.event.contact</code>.
     */
    public String getContact();

    /**
     * Setter for <code>public.event.date</code>.
     */
    public IEvent setDate(Timestamp value);

    /**
     * Getter for <code>public.event.date</code>.
     */
    public Timestamp getDate();

    /**
     * Setter for <code>public.event.details</code>.
     */
    public IEvent setDetails(String value);

    /**
     * Getter for <code>public.event.details</code>.
     */
    public String getDetails();

    /**
     * Setter for <code>public.event.location</code>.
     */
    public IEvent setLocation(String value);

    /**
     * Getter for <code>public.event.location</code>.
     */
    public String getLocation();

    /**
     * Setter for <code>public.event.max_participants</code>.
     */
    public IEvent setMaxParticipants(Integer value);

    /**
     * Getter for <code>public.event.max_participants</code>.
     */
    public Integer getMaxParticipants();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IEvent
     */
    public void from(meta.tables.interfaces.IEvent from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IEvent
     */
    public <E extends meta.tables.interfaces.IEvent> E into(E into);
}
