/*
 * This file is generated by jOOQ.
 */
package meta.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFlywaySchemaHistory extends Serializable {

    /**
     * Setter for <code>public.flyway_schema_history.installed_rank</code>.
     */
    public IFlywaySchemaHistory setInstalledRank(Integer value);

    /**
     * Getter for <code>public.flyway_schema_history.installed_rank</code>.
     */
    public Integer getInstalledRank();

    /**
     * Setter for <code>public.flyway_schema_history.version</code>.
     */
    public IFlywaySchemaHistory setVersion(String value);

    /**
     * Getter for <code>public.flyway_schema_history.version</code>.
     */
    public String getVersion();

    /**
     * Setter for <code>public.flyway_schema_history.description</code>.
     */
    public IFlywaySchemaHistory setDescription(String value);

    /**
     * Getter for <code>public.flyway_schema_history.description</code>.
     */
    public String getDescription();

    /**
     * Setter for <code>public.flyway_schema_history.type</code>.
     */
    public IFlywaySchemaHistory setType(String value);

    /**
     * Getter for <code>public.flyway_schema_history.type</code>.
     */
    public String getType();

    /**
     * Setter for <code>public.flyway_schema_history.script</code>.
     */
    public IFlywaySchemaHistory setScript(String value);

    /**
     * Getter for <code>public.flyway_schema_history.script</code>.
     */
    public String getScript();

    /**
     * Setter for <code>public.flyway_schema_history.checksum</code>.
     */
    public IFlywaySchemaHistory setChecksum(Integer value);

    /**
     * Getter for <code>public.flyway_schema_history.checksum</code>.
     */
    public Integer getChecksum();

    /**
     * Setter for <code>public.flyway_schema_history.installed_by</code>.
     */
    public IFlywaySchemaHistory setInstalledBy(String value);

    /**
     * Getter for <code>public.flyway_schema_history.installed_by</code>.
     */
    public String getInstalledBy();

    /**
     * Setter for <code>public.flyway_schema_history.installed_on</code>.
     */
    public IFlywaySchemaHistory setInstalledOn(Timestamp value);

    /**
     * Getter for <code>public.flyway_schema_history.installed_on</code>.
     */
    public Timestamp getInstalledOn();

    /**
     * Setter for <code>public.flyway_schema_history.execution_time</code>.
     */
    public IFlywaySchemaHistory setExecutionTime(Integer value);

    /**
     * Getter for <code>public.flyway_schema_history.execution_time</code>.
     */
    public Integer getExecutionTime();

    /**
     * Setter for <code>public.flyway_schema_history.success</code>.
     */
    public IFlywaySchemaHistory setSuccess(Boolean value);

    /**
     * Getter for <code>public.flyway_schema_history.success</code>.
     */
    public Boolean getSuccess();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IFlywaySchemaHistory
     */
    public void from(meta.tables.interfaces.IFlywaySchemaHistory from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IFlywaySchemaHistory
     */
    public <E extends meta.tables.interfaces.IFlywaySchemaHistory> E into(E into);
}
