/*
 * This file is generated by jOOQ.
 */
package meta.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IParticipant extends Serializable {

    /**
     * Setter for <code>public.participant.id</code>.
     */
    public IParticipant setId(Long value);

    /**
     * Getter for <code>public.participant.id</code>.
     */
    public Long getId();

    /**
     * Setter for <code>public.participant.name</code>.
     */
    public IParticipant setName(String value);

    /**
     * Getter for <code>public.participant.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.participant.email</code>.
     */
    public IParticipant setEmail(String value);

    /**
     * Getter for <code>public.participant.email</code>.
     */
    public String getEmail();

    /**
     * Setter for <code>public.participant.verification_token</code>.
     */
    public IParticipant setVerificationToken(String value);

    /**
     * Getter for <code>public.participant.verification_token</code>.
     */
    public String getVerificationToken();

    /**
     * Setter for <code>public.participant.event_id</code>.
     */
    public IParticipant setEventId(Long value);

    /**
     * Getter for <code>public.participant.event_id</code>.
     */
    public Long getEventId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IParticipant
     */
    public void from(meta.tables.interfaces.IParticipant from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IParticipant
     */
    public <E extends meta.tables.interfaces.IParticipant> E into(E into);
}
