/*
 * This file is generated by jOOQ.
 */
package meta.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;

import meta.tables.interfaces.IEvent;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Event implements IEvent {

    private static final long serialVersionUID = 1405999308;

    private Long      id;
    private String    name;
    private String    contact;
    private Timestamp date;
    private String    details;
    private String    location;
    private Integer   maxParticipants;

    public Event() {}

    public Event(IEvent value) {
        this.id = value.getId();
        this.name = value.getName();
        this.contact = value.getContact();
        this.date = value.getDate();
        this.details = value.getDetails();
        this.location = value.getLocation();
        this.maxParticipants = value.getMaxParticipants();
    }

    public Event(
        Long      id,
        String    name,
        String    contact,
        Timestamp date,
        String    details,
        String    location,
        Integer   maxParticipants
    ) {
        this.id = id;
        this.name = name;
        this.contact = contact;
        this.date = date;
        this.details = details;
        this.location = location;
        this.maxParticipants = maxParticipants;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public Event setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public Event setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getContact() {
        return this.contact;
    }

    @Override
    public Event setContact(String contact) {
        this.contact = contact;
        return this;
    }

    @Override
    public Timestamp getDate() {
        return this.date;
    }

    @Override
    public Event setDate(Timestamp date) {
        this.date = date;
        return this;
    }

    @Override
    public String getDetails() {
        return this.details;
    }

    @Override
    public Event setDetails(String details) {
        this.details = details;
        return this;
    }

    @Override
    public String getLocation() {
        return this.location;
    }

    @Override
    public Event setLocation(String location) {
        this.location = location;
        return this;
    }

    @Override
    public Integer getMaxParticipants() {
        return this.maxParticipants;
    }

    @Override
    public Event setMaxParticipants(Integer maxParticipants) {
        this.maxParticipants = maxParticipants;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Event (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(contact);
        sb.append(", ").append(date);
        sb.append(", ").append(details);
        sb.append(", ").append(location);
        sb.append(", ").append(maxParticipants);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IEvent from) {
        setId(from.getId());
        setName(from.getName());
        setContact(from.getContact());
        setDate(from.getDate());
        setDetails(from.getDetails());
        setLocation(from.getLocation());
        setMaxParticipants(from.getMaxParticipants());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IEvent> E into(E into) {
        into.from(this);
        return into;
    }
}
