/*
 * This file is generated by jOOQ.
 */
package meta.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;

import meta.tables.interfaces.IFlywaySchemaHistory;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlywaySchemaHistory implements IFlywaySchemaHistory {

    private static final long serialVersionUID = 1822943786;

    private Integer   installedRank;
    private String    version;
    private String    description;
    private String    type;
    private String    script;
    private Integer   checksum;
    private String    installedBy;
    private Timestamp installedOn;
    private Integer   executionTime;
    private Boolean   success;

    public FlywaySchemaHistory() {}

    public FlywaySchemaHistory(IFlywaySchemaHistory value) {
        this.installedRank = value.getInstalledRank();
        this.version = value.getVersion();
        this.description = value.getDescription();
        this.type = value.getType();
        this.script = value.getScript();
        this.checksum = value.getChecksum();
        this.installedBy = value.getInstalledBy();
        this.installedOn = value.getInstalledOn();
        this.executionTime = value.getExecutionTime();
        this.success = value.getSuccess();
    }

    public FlywaySchemaHistory(
        Integer   installedRank,
        String    version,
        String    description,
        String    type,
        String    script,
        Integer   checksum,
        String    installedBy,
        Timestamp installedOn,
        Integer   executionTime,
        Boolean   success
    ) {
        this.installedRank = installedRank;
        this.version = version;
        this.description = description;
        this.type = type;
        this.script = script;
        this.checksum = checksum;
        this.installedBy = installedBy;
        this.installedOn = installedOn;
        this.executionTime = executionTime;
        this.success = success;
    }

    @Override
    public Integer getInstalledRank() {
        return this.installedRank;
    }

    @Override
    public FlywaySchemaHistory setInstalledRank(Integer installedRank) {
        this.installedRank = installedRank;
        return this;
    }

    @Override
    public String getVersion() {
        return this.version;
    }

    @Override
    public FlywaySchemaHistory setVersion(String version) {
        this.version = version;
        return this;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public FlywaySchemaHistory setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public String getType() {
        return this.type;
    }

    @Override
    public FlywaySchemaHistory setType(String type) {
        this.type = type;
        return this;
    }

    @Override
    public String getScript() {
        return this.script;
    }

    @Override
    public FlywaySchemaHistory setScript(String script) {
        this.script = script;
        return this;
    }

    @Override
    public Integer getChecksum() {
        return this.checksum;
    }

    @Override
    public FlywaySchemaHistory setChecksum(Integer checksum) {
        this.checksum = checksum;
        return this;
    }

    @Override
    public String getInstalledBy() {
        return this.installedBy;
    }

    @Override
    public FlywaySchemaHistory setInstalledBy(String installedBy) {
        this.installedBy = installedBy;
        return this;
    }

    @Override
    public Timestamp getInstalledOn() {
        return this.installedOn;
    }

    @Override
    public FlywaySchemaHistory setInstalledOn(Timestamp installedOn) {
        this.installedOn = installedOn;
        return this;
    }

    @Override
    public Integer getExecutionTime() {
        return this.executionTime;
    }

    @Override
    public FlywaySchemaHistory setExecutionTime(Integer executionTime) {
        this.executionTime = executionTime;
        return this;
    }

    @Override
    public Boolean getSuccess() {
        return this.success;
    }

    @Override
    public FlywaySchemaHistory setSuccess(Boolean success) {
        this.success = success;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FlywaySchemaHistory (");

        sb.append(installedRank);
        sb.append(", ").append(version);
        sb.append(", ").append(description);
        sb.append(", ").append(type);
        sb.append(", ").append(script);
        sb.append(", ").append(checksum);
        sb.append(", ").append(installedBy);
        sb.append(", ").append(installedOn);
        sb.append(", ").append(executionTime);
        sb.append(", ").append(success);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IFlywaySchemaHistory from) {
        setInstalledRank(from.getInstalledRank());
        setVersion(from.getVersion());
        setDescription(from.getDescription());
        setType(from.getType());
        setScript(from.getScript());
        setChecksum(from.getChecksum());
        setInstalledBy(from.getInstalledBy());
        setInstalledOn(from.getInstalledOn());
        setExecutionTime(from.getExecutionTime());
        setSuccess(from.getSuccess());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IFlywaySchemaHistory> E into(E into) {
        into.from(this);
        return into;
    }
}
