/*
 * This file is generated by jOOQ.
 */
package meta.tables.pojos;


import java.sql.Timestamp;

import javax.annotation.Generated;

import meta.tables.interfaces.IMailingList;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MailingList implements IMailingList {

    private static final long serialVersionUID = -2080058916;

    private Long      id;
    private String    affiliation;
    private String    email;
    private String    firstName;
    private String    lastName;
    private Timestamp created;
    private Boolean   receivesMail;

    public MailingList() {}

    public MailingList(IMailingList value) {
        this.id = value.getId();
        this.affiliation = value.getAffiliation();
        this.email = value.getEmail();
        this.firstName = value.getFirstName();
        this.lastName = value.getLastName();
        this.created = value.getCreated();
        this.receivesMail = value.getReceivesMail();
    }

    public MailingList(
        Long      id,
        String    affiliation,
        String    email,
        String    firstName,
        String    lastName,
        Timestamp created,
        Boolean   receivesMail
    ) {
        this.id = id;
        this.affiliation = affiliation;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.created = created;
        this.receivesMail = receivesMail;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public MailingList setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getAffiliation() {
        return this.affiliation;
    }

    @Override
    public MailingList setAffiliation(String affiliation) {
        this.affiliation = affiliation;
        return this;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public MailingList setEmail(String email) {
        this.email = email;
        return this;
    }

    @Override
    public String getFirstName() {
        return this.firstName;
    }

    @Override
    public MailingList setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    @Override
    public String getLastName() {
        return this.lastName;
    }

    @Override
    public MailingList setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    @Override
    public Timestamp getCreated() {
        return this.created;
    }

    @Override
    public MailingList setCreated(Timestamp created) {
        this.created = created;
        return this;
    }

    @Override
    public Boolean getReceivesMail() {
        return this.receivesMail;
    }

    @Override
    public MailingList setReceivesMail(Boolean receivesMail) {
        this.receivesMail = receivesMail;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MailingList (");

        sb.append(id);
        sb.append(", ").append(affiliation);
        sb.append(", ").append(email);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(created);
        sb.append(", ").append(receivesMail);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IMailingList from) {
        setId(from.getId());
        setAffiliation(from.getAffiliation());
        setEmail(from.getEmail());
        setFirstName(from.getFirstName());
        setLastName(from.getLastName());
        setCreated(from.getCreated());
        setReceivesMail(from.getReceivesMail());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IMailingList> E into(E into) {
        into.from(this);
        return into;
    }
}
