/*
 * This file is generated by jOOQ.
 */
package meta.tables.pojos;


import javax.annotation.Generated;

import meta.tables.interfaces.IParticipant;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Participant implements IParticipant {

    private static final long serialVersionUID = -576842373;

    private Long   id;
    private String name;
    private String email;
    private String verificationToken;
    private Long   eventId;

    public Participant() {}

    public Participant(IParticipant value) {
        this.id = value.getId();
        this.name = value.getName();
        this.email = value.getEmail();
        this.verificationToken = value.getVerificationToken();
        this.eventId = value.getEventId();
    }

    public Participant(
        Long   id,
        String name,
        String email,
        String verificationToken,
        Long   eventId
    ) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.verificationToken = verificationToken;
        this.eventId = eventId;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public Participant setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public Participant setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public Participant setEmail(String email) {
        this.email = email;
        return this;
    }

    @Override
    public String getVerificationToken() {
        return this.verificationToken;
    }

    @Override
    public Participant setVerificationToken(String verificationToken) {
        this.verificationToken = verificationToken;
        return this;
    }

    @Override
    public Long getEventId() {
        return this.eventId;
    }

    @Override
    public Participant setEventId(Long eventId) {
        this.eventId = eventId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Participant (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(verificationToken);
        sb.append(", ").append(eventId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IParticipant from) {
        setId(from.getId());
        setName(from.getName());
        setEmail(from.getEmail());
        setVerificationToken(from.getVerificationToken());
        setEventId(from.getEventId());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IParticipant> E into(E into) {
        into.from(this);
        return into;
    }
}
