/*
 * This file is generated by jOOQ.
 */
package meta;


import javax.annotation.Generated;

import meta.tables.Event;
import meta.tables.FlywaySchemaHistory;
import meta.tables.MailingList;
import meta.tables.Participant;
import meta.tables.records.EventRecord;
import meta.tables.records.FlywaySchemaHistoryRecord;
import meta.tables.records.MailingListRecord;
import meta.tables.records.ParticipantRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<EventRecord, Long> IDENTITY_EVENT = Identities0.IDENTITY_EVENT;
    public static final Identity<MailingListRecord, Long> IDENTITY_MAILING_LIST = Identities0.IDENTITY_MAILING_LIST;
    public static final Identity<ParticipantRecord, Long> IDENTITY_PARTICIPANT = Identities0.IDENTITY_PARTICIPANT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EventRecord> EVENT_PKEY = UniqueKeys0.EVENT_PKEY;
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final UniqueKey<MailingListRecord> MAILING_LIST_PKEY = UniqueKeys0.MAILING_LIST_PKEY;
    public static final UniqueKey<ParticipantRecord> PARTICIPANT_PKEY = UniqueKeys0.PARTICIPANT_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<EventRecord, Long> IDENTITY_EVENT = Internal.createIdentity(Event.EVENT, Event.EVENT.ID);
        public static Identity<MailingListRecord, Long> IDENTITY_MAILING_LIST = Internal.createIdentity(MailingList.MAILING_LIST, MailingList.MAILING_LIST.ID);
        public static Identity<ParticipantRecord, Long> IDENTITY_PARTICIPANT = Internal.createIdentity(Participant.PARTICIPANT, Participant.PARTICIPANT.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<EventRecord> EVENT_PKEY = Internal.createUniqueKey(Event.EVENT, "event_pkey", Event.EVENT.ID);
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
        public static final UniqueKey<MailingListRecord> MAILING_LIST_PKEY = Internal.createUniqueKey(MailingList.MAILING_LIST, "mailing_list_pkey", MailingList.MAILING_LIST.ID);
        public static final UniqueKey<ParticipantRecord> PARTICIPANT_PKEY = Internal.createUniqueKey(Participant.PARTICIPANT, "participant_pkey", Participant.PARTICIPANT.ID);
    }
}
